// <auto-generated />
namespace IQ.Santos.Ngo.Beertap.Persistence
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Beertap_04012016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Beertap_04012016));
        
        string IMigrationMetadata.Id
        {
            get { return "201604011155267_Beertap_04012016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
